### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kokoro-kusakabe** [kokoro-kusakabe/furima-30573#10]
フリマアプリの挙動確認をお願いします。

自身のフリマアプリのURL
　https://furima-30573.herokuapp.com/
Basic認証のID
　shu30573
Basic認証のパスワード
　14qSgN5dk
出品者用のメールアドレスとパスワード
　Email　　　　　a@a.jp
　Password　　　11111q
購入者用のメールアドレスとパスワード
　Email　　　　　b@b.jp
　Password　　　22222q
購入用カードの番号・期限・セキュリティコード
　カード番号　4242424242424242
　有効期限　　3/33
　CVC　　　　123

**Comment by keisukekodama** [comment]
提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**・商品出品ができない**
商品出品ページに遷移できません。
修正しましょう！

修正し次第、以下の完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
また、他の商品出品機能、商品購入、商品詳細機能などのチェックは修正完了後行います。

https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform

**Comment by kokoro-kusakabe** [comment]
出品できる場合はどうすれば良いのですか？
修正しなくても出品可能なのですが。
出品URL
https://furima-30573.herokuapp.com/items/new

**Comment by mo1015** [comment]
再提出とご質問ありがとうございます！
挙動確認させて頂いたところ、前回同様に商品出品ができない状況でした。
（出品ボタンを押しても出品ページに遷移しない）

デプロイを含め再度、本番環境で実装できているか確認をお願いできますでしょうか？
ローカル環境で実装ができていても、本番環境に反映されていないと挙動確認ができないためです。

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kokoro-kusakabe** [comment]
出品ボタンの画像にリンクの付与の修正をしました。
再度レビューをお願いします

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
